# Generated by Django 3.2.4 on 2021-08-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('bloodgroup', models.CharField(max_length=3)),
                ('lastdonationdate', models.DateField()),
            ],
        ),
    ]
