# Generated by Django 3.2.4 on 2021-10-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='testbldgrp',
            field=models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('Ab+', 'Ab+')], default=0, max_length=9),
            preserve_default=False,
        ),
    ]
