# Generated by Django 3.2.4 on 2021-10-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_donor_testbldgrp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='testbldgrp',
        ),
        migrations.AlterField(
            model_name='donor',
            name='bloodgroup',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('Ab+', 'Ab+'), ('Ab-', 'Ab-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
    ]
