# Generated by Django 3.2.4 on 2021-10-19 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_donor_bloodgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='lastdonationdate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('[a-z|\\s|A-Z]*', 'Only characters.')]),
        ),
        migrations.AlterField(
            model_name='donor',
            name='phone',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator('[01][0-9]{9}', 'correct sequence plz')]),
        ),
    ]
