# Generated by Django 3.2.4 on 2021-10-19 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20211019_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('[^0-9]*', 'Only characters.')]),
        ),
    ]
