# Generated by Django 3.2.4 on 2021-10-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_donor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donor',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
