# Generated by Django 3.2.4 on 2021-10-24 05:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20211021_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='bloodgroup',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('Ab+', 'Ab+'), ('Ab-', 'Ab-'), ('O+', 'O+'), ('O-', 'O-')], max_length=4),
        ),
        migrations.AlterField(
            model_name='donor',
            name='lastdonationdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='donor',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'no characters')]),
        ),
    ]
