# Generated by Django 3.2.4 on 2021-11-05 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20211024_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='lastdonationdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z|\\s]+$', 'no numeric')]),
        ),
        migrations.AlterField(
            model_name='donor',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
